---
title: "City Highways - Parking Occupancy"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: logo.png
    favicon: logo.png
    css: styles.css
---
 
```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(lubridate)
library(leaflet)
library(readr)
library(sf)
library(leafgl)
library(DT) 
library(stringr)
```

```{r data_processing, results='hide'}
wards <- read_sf("../../../organised/data/clean_data_files/westminster_boundary_files/London-wards-2018/London-wards-2018_ESRI/London_Ward.shp")
wards <- wards %>%
  dplyr::filter(DISTRICT=="City of Westminster") %>%
  st_transform(4326)

bays <- read_sf("~/Desktop/bay_occupancy_data/bay_occupancy.shp")

pal <- leaflet::colorNumeric("RdYlBu", domain = c(0,101), n = 9, reverse = T)
pal_r <- leaflet::colorNumeric("RdYlBu", domain = c(0,101), n = 9)

bays_buffer <- bays %>%
  st_transform(27700) %>%
  st_buffer(5, nQuadSegs = 1) %>% 
  st_transform(4326) %>%
  mutate(occ = ifelse(occ > 100, 100, occ)) %>%
  select(street, geometry, occ, Rstrct_, no_bays)

# Car Club Bays
carclub <- read_csv("../../../CarClub/cc_locations.csv")
carclub <- carclub %>%
  dplyr::filter(lat > -0.5)
```

Map {data-icon="fa-map"}
=====================================  

### Page 1 {.no-padding .no-title}

```{r}
leaflet(elementId = "full_map", options = leafletOptions(preferCanvas = TRUE)) %>% 
  addProviderTiles(providers$CartoDB.DarkMatter) %>%
  #addGlPoints(data=st_as_sf(data.frame(id=c(1,2,3,4,5), lat=c(51.1,51.2,51.3,51.4,51.5), lon=c(1.1,1.2,1.3,1.5,1.6)), coords=c("lon", "lat")))
  #addPolygons(data=bays, fill="blue", fillOpacity=1, weight=1.5, color = ~pal(occ), label=~round(occ,1))
  addPolygons(data=wards, fill=F, weight=0.5, color="white", opacity=0.9) %>%
  addGlPolygons(data=dplyr::filter(bays_buffer, Rstrct_=="Shared Use Bay"),color = ~pal(occ), fillColor=~pal(occ), popup=~paste(round(occ,1), "% Occupancy", sep=""), group="Shared Use Bay") %>%
    addGlPolygons(data=dplyr::filter(bays_buffer, Rstrct_=="Pay by Phone Bay"),color = ~pal(occ), fillColor=~pal(occ), popup=~paste(round(occ,1), "% Occupancy", sep=""), group="Pay by Phone Bay") %>%
    addGlPolygons(data=dplyr::filter(bays_buffer, Rstrct_=="Resident Bay"),color = ~pal(occ), fillColor=~pal(occ), popup=~paste(round(occ,1), "% Occupancy", sep=""), group="Resident Bay") %>%
  #addGlPolygons(data=dplyr::filter(bays_buffer, is.na(occ)),color = "grey", fillColor="grey", popup=~paste(round(occ,1), "% Occupancy", sep=""), group="Resident Bay") %>%
  addCircles(data=carclub, lat=~lon, lng=~lat, stroke=F, fillColor = "white", radius=20, fillOpacity = 0.9, label=~Location, group="Car Club Bays") %>%
  addLayersControl(overlayGroups = c("Resident Bay", "Pay by Phone Bay", "Shared Use Bay", "Car Club Bays"), position = "topright", options=layersControlOptions(collapsed = FALSE)) %>%
  addLegend("bottomright", pal = pal_r, values = ~occ,
    title = "Occupancy",
    opacity = 1,
    labFormat = labelFormat(suffix = "%", transform = function(x) sort(x, decreasing = TRUE)),
    data=bays_buffer,
    na.label=""
  )
```

Data {data-icon="fa-table"}
=====================================

### data {.no-title}

```{r}
bays_buffer %>%
  as.data.frame() %>%
  select(-geometry) %>%
  distinct() %>%
  dplyr::arrange(street) %>%
  dplyr::mutate(occ = round(occ,1)) %>%
  dplyr::mutate(street = str_to_title(street)) %>%
  dplyr::rename("Street"="street", "Occupancy (%)"="occ", "Bay Type"="Rstrct_", "No. Bays"="no_bays") %>%
  datatable(extensions = "Buttons", options = list(dom = 'Bfrtip', buttons=c("excel", "csv")))
```

About {data-icon="fa-bars"}
===================================== 

#### About title

* Author: Westminster City Highways
* Date Created: 2021-02-23
* Date Updated: `r lubridate::today()`

<!-- Description of Report -->

